services:
  - type: web
    name: moneymanager-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://moneymanager-backend.onrender.com
